#pragma config(Sensor, S3,     sonarSensor,    sensorEV3_Ultrasonic)
#pragma config(Motor,  motorB,          leftMotor,     tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorC,          rightMotor,    tmotorEV3_Large, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
 int period = 10000;
 int timer;
 int reference = 100;
 int measured;
 int error;
 float gain = -0.5;
 int power;
 timer = period;
 while(timer)
 	{
 	 measured = SensorValue[sonarSensor];
 	 error = reference - measured;
	 power = gain * error;
	 motor[leftMotor] = power;
	 motor[rightMotor] = power;
	 displayCenteredBigTextLine(2, "Measured : %3d", measured);
	 displayCenteredBigTextLine(6, "Error : %3d", error );
	 displayCenteredBigTextLine(10, "Power : %3d", power );
	 timer = period;
 	}
}
