#pragma config(StandardModel, "EV3_REMBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


int reference =100;
int measured;
int error=1;
int error_sum;
int previous_error = 0;
int error_diff;
float gain_p = -0.2;
float gain_i = -0.5;
float gain_d = -0.8;
int powerc;


task main()
{

while(error != 0){
measured =getUSDistance(sonarSensor);
error = reference - measured;
error_sum = error_sum + error;
error_diff = error- previous_error;
previous_error = error;
powerc = gain_p* error + gain_i*error_sum + gain_d* error_diff;

setMotorSpeed(motorC, powerc);
setMotorSpeed(motorB, powerc);
/**
waitUntil(getUSDistance(sonarSensor)< 30);
setMotorSpeed(motorB, 0);
setMotorSpeed(motorC, 0); **/
  wait1Msec( 10 );
}

}
